FROM python:3.12-alpine AS builder

WORKDIR /app

RUN apk add --no-cache \
    build-base \
    libffi-dev \
    openssl-dev

COPY requirements-prod.txt .

RUN pip install --no-cache-dir \
    --prefix=/install \
    -r requirements-prod.txt


FROM python:3.12-alpine

WORKDIR /app

ENV PYTHONPATH=/app

RUN apk add --no-cache \
    libssl3 \
    ca-certificates

COPY --from=builder /install /usr/local

COPY src ./src

CMD ["python", "-m", "src.cmd.bot.bot"]
